name:                ComputerV2
version:             0.1.0.0
github:              "glegendr/ComputerV2"
license:             BSD3
author:              "glegendr"
maintainer:          "glegendr@student.42.fr"
copyright:           "2020 glegendr"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/glegendr/ComputerV2#readme>

dependencies:
- base >= 4.7 && < 5
- split
- unordered-containers
- Chart-diagrams
- Chart-cairo
- time
- directory
- Chart

library:
  source-dirs: src

executables:
  ComputerV2:
    main:                main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ComputerV2